#!/usr/bin/env bash
logDosyasi="$1"
exec 3>&1 1>"$logDosyasi" 2>&1
trap 'echo "${FUNCNAME-main} $LINENO. satırda [${BASH_COMMAND}] komutu ($?) kodu ile hata verdi." >&3' ERR
trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Is)]  "; set -x' DEBUG
