#!/bin/bash
#
# TODO goruntu için test yaz
# Çevre değişkenleri
export PATH="$PATH:/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/araclar: \
    /disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/mplabx/"
export urtotm_calismaDizini="/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/test-araclar"
export urtotm_projeDizini="/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/test-araclar/goruntu-projesi"
export urtotm_yedekDizini="/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/test-araclar/yedekler"
export urtotm_projeAdi="Goruntu-Projesi" # Kurulum sırasında istenecek, boşluklar tirelerle değiştirilecek
export urtotm_dialogBaslik="${urtotm_projeAdi} - Üretim Otomasyonu"
export urtotm_projeUrtotmDizini="/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/test-araclar/.urtotm"


# source etkilesim
# echo "PATH $PATH"
# echo "PWD $PWD"
# mesajGoster bilgi "Yayınla Test" "Test başlıyor..."
# goruntu
# goruntu post-commit
goruntu post-merge
