#!/usr/bin/env bash
#
# Görüntü için birim testi
test -f test_ilkle && source $_

# source etkilesim
# echo "PATH $PATH"
# echo "PWD $PWD"
# mesajGoster bilgi "Yayınla Test" "Test başlıyor..."
goruntu
goruntu post-commit
goruntu post-merge
