#!/bin/bash
#
# Etkileşim testleri
# Çevre değişkenleri
export PATH+=:/disk/Projeler/UretimOtomasyonu/Bash/araclar/araclar

# Geçici dosyayı kur
dosya=$((mktemp) 2>/dev/null) || dosya=/tmp/logcu$$
trap "rm -f $dosya" 0 # $SIG_NONE $SIG_HUP $SIG_INT $SIG_QUIT $SIG_TERM
echo "Log dosyası: '$dosya'"
source logcu "$dosya"

# Hatayı tetikle
echo "Logcu test ediliyor......$(date)"
mkdir ~/abc/bca/ccc
kotukomut
kotukomut1

exec &>/dev/tty # Çıkışları yeniden terminale yönlendir
echo "Log dosyası içeriği:"
echo "--------------------"
cat "$dosya"
