#!/bin/bash
#
# Etkileşim testleri
# Çevre değişkenleri
PATH=/disk/Projeler/UretimOtomasyonu/Bash/araclar/araclar:$PATH

source etkilesim


# mesajGoster bilgi "Bilgi Başlığı" "Bilgi mesajı."
# mesajGoster bilgi "Üretim Otomasyonu" "Gereken tüm uygulamalar sistemde yüklü. Üretim Otomasyonu şimdi kurulacak."
# yaziGoster "/disk/Projeler/UretimOtomasyonu/Bash/logs/rsync-log-20231207174858"
# evetHayirGoster "Dosyaları Sil" "Dosyalar silinsin mi?" || echo "Yanıt hayır"


secenekGoster "Seçenek Başlığı" "Seçenek açıklaması" "11 22 33 44 55 66 77"
read -u 4 girdi
echo "Seçenek göster seçim: $girdi"

dizinSec "Bir dizin seç"
read -r girdi <&4
echo "Dizin seç seçim: $girdi"

girdiAl "Bilgi gir" "1.satır\n2.satır\n3.satır"
read -r girdi <&4
echo "Girdi al girdi: $girdi"
